name: Ozkan_Build_Final_v1

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev openjdk-17-jdk
          pip install --upgrade pip
          pip install Cython==0.29.33 buildozer

      - name: Manual SDK Fix (Cmdline-tools)
        run: |
          # Buildozer'ın bulamadığı sdkmanager yollarını manuel oluşturuyoruz
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip
          mv cmdline-tools/* $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/
          
          # Lisansları kökten kabul et
          mkdir -p $HOME/.android
          touch $HOME/.android/repositories.cfg
          yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk --licenses

      - name: Build with Buildozer
        run: |
          # Buildozer'ı yolu görmesi için zorlayarak başlatıyoruz
          buildozer -v android debug
        env:
          ACCEPT_SDK_LICENSE: 1
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          
